[project]
name = "cube-standard"
version = "0.1.0"
description = "Common Unified Benchmark Environments"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.1.0",
    "pydantic>=2.12.5",
]
